steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west9-docker.pkg.dev/cours-463409/motus/motus:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west9-docker.pkg.dev/cours-463409/motus/motus:$SHORT_SHA']

  # Déploiement optionnel, à adapter selon votre cible (GKE, Cloud Run, etc.)

images:
  - 'europe-west9-docker.pkg.dev/cours-463409/motus/motus:$SHORT_SHA'
