name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/motus:$GITHUB_SHA .

      - name: Push image to GCR
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/motus:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy motus \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/motus:$GITHUB_SHA \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated
