name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west9-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t europe-west9-docker.pkg.dev/cours-463409/motus/motus:$GITHUB_SHA .

      - name: Push image to Artifact Registry
        run: docker push europe-west9-docker.pkg.dev/cours-463409/motus/motus:$GITHUB_SHA
